### ISSUE TITLE
Incorrect calculation for Time-Lost jewel and Titan's Hulking Form

### ISSUE THREAD

**Issue by kenblair** [PathOfBuildingCommunity/PathOfBuilding-PoE2#478]
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues?q=is%3Aissue)

### Check for support

- [x] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

In-game Hulking Form (+50%) and 30% increased Effect of Small Passive Skills in Radius stack for a multiplier of 1.8 _**and**_ they multiply the bonuses from the gem as well.

10% increased damage (from passive node) is 18%
5% increased block (from passive node) is 9%
2% increased damage (from Time-Lost Sapphire) is 3.6%
3% increased ES (from Time-Lost Sapphire) is 5.4%
8% increased life (from passive node) is 14.4%

Example 1:

![Image](https://github.com/user-attachments/assets/c1fa0c38-4b09-4d89-8231-df7ee45f7fba)

![Image](https://github.com/user-attachments/assets/890a430f-3df9-4c8c-bee5-28f46db52aa5)

Example 2:

![Image](https://github.com/user-attachments/assets/247c79bd-6aa3-48c1-b0b4-cc6b83d7191b)

![Image](https://github.com/user-attachments/assets/b4cc1caa-e457-4355-b05b-aa4c62769b52)

### What is the value from the calculation in Path of Building?

Path of Building 0.2.0 is only showing the 50% bonus from Hulking Form and is not applying the 30% bonus from Time-Lost jewel at all.

10% increased damage (from passive node) is only 15% total in calcs, should be 18%
2% increased damage (from Time-Lost Sapphire) is only 3% total in calcs, should be 3.6%
8% increased life (from passive node) is only 12% total in calcs, should be 14.4%
7% chaos resist (from passive node) is only 10%, should be 12.6%

Example 1:

![Image](https://github.com/user-attachments/assets/58af7d2e-107b-47ba-a2bf-a26bf47b02ca)

![Image](https://github.com/user-attachments/assets/26f6596a-1b4f-48ab-97ee-ebc518b266fa)

![Image](https://github.com/user-attachments/assets/a862abd9-90f8-404c-b16a-5ad404903d9b)

Total increased damage from Minion Life and Chaos Resistance is 3% but should be 3.6%.
Total increased damage from _**each**_ Minion Damage node is 18% (15 + 3) but should be 21.6% (18 + 3.6).

![Image](https://github.com/user-attachments/assets/d9f26bdc-89a7-4a20-ab1a-e9528dac0f0f)

Total increased life from Minion Life and Chaos Resistance is 12% but should be 14.4%.

Example 2:

![Image](https://github.com/user-attachments/assets/93ebdb7f-5202-400f-a89d-b8cd07970868)

![Image](https://github.com/user-attachments/assets/c1694592-0d20-430f-9447-b6928632dfb8)

Increased block is 7% total should be 9%.

### How to reproduce the issue

1. Create a Titan.
2. Allocate Hulking Form.
3. Add a Time-Lost jewel.
4. Calculations do not show correct bonus.

### Character build code

```shell
eNrtPVlz20jOz6NfwVLVVu2WFZv3kbJnSz7jxIo1khNP5iVFiy2JE4qUefjI1v73D-jmKbEpSs7U55mdPDhSN4BGA2gADXZTh_9-WnjCAwkjN_CPutK-2BWIPwkc158ddT_dnL8xu__-uXM4tOP59fQ4cT3skX_u_HRIvwgeeSDeUdeSu8LEs6Poo70gR91bOwzdIOwKdjQhvnNS9Ny4se13hdgOZyT-nI0rfpUAf26H9iQm4RXS7CdxMAgcQInDhHSFhe3642DyjcQXYZAsgdeu8OCSRwZzORhej266wNdPh0PPfibhOLZjIYI_R93-JHYfyMD1Yawrd-HGgGl7CaCJ3QMOCojEnpF3W8AeJ2EUn9oL-LgZZ7wkxNkMdhK68SDxYnfpuSTM4WUePPB7Mrf9ScGBJHKJ3wSx7Z0Ox5vZYJBBC1ncuvH82IO5taKL0Jcz341Ja_Bh4EaBvxXXrYBPEs8Dy24FOyIRCR_s2G3JyEmwuHP9ljIZ2L59EkRxO8ghCWGBxVshjMkkgDW57RhbYl65U9Iecqt5pAjbcrPbPM7GbeG2JrwbQyNwMO0gx0HitYSMC-ciSQrf8O9bQp6Sp8JbcYe99AveJEtrGLYKKfGHfQhwWbZ0DmfvhgVVU9G1fcXUJE0XTYuHN5w_R-7E9gb2k7tIFuBwb-xvpBhQE1WTb4SzeeyDl-EhSzqMzcM-d0OyE-JJ4Dm7Ic7tIOJiSqpsNi23Qv-aZjTEwclbhL70JwVppYnuJz-k_rcUP5tGQJQRLC8M0nceaY1TDJMu0zYhlQ02I3464nOBpBr7jeK6ImQyv4AkZ2THpJ1jLglMFxsljNBlCTeSrRFw0wBVlC2EhYj1wjLMfasJa0tZjZduWErkFFNqhqyzMFNvi7MqAUPbF2GVSbphGdxZnfkknD2P5y7xSlI3FKkNQia_E3vZCpeaRJlA2TRkUW43Zp3ixDaoW2pv1CqhRqh6nuR9rurOHuyoHC1kudlRpfDtVhKBNBgQHLKSkXMxhmHwO4GtircdWj9cBEkRlFXVbJ4Eg6_4W0ncFO7YvmZEnGRSia8KX-PTKaH7rmMPdm0rkzGUfUvfiAnsel4dOl8WcWxPvp0Gzqy1-OggW2FU-RsnyyUsfbSLtgQwksMewo3KTmIz8DWYdXmJNwb81vQL4FX6krExkWk9ygrG2lBqYw6yMoxutIBuLa1cnQPwGwvw3HRvPghKfnhfNrjWeg4bx1YbOwrYcjc6DB6B-zkWSaLtoCFdKxYnl5WQ-N-fW9OvgLca4Mx3khAXQ-sxVjFaDbO5sMP61os1K3UaXdIg9zd0WYMYrfBwq0UbsApLKf79UKS10oxh6eK-pSmypVmW1YwWtBBDbZ2m3SD1RZv2uOsVnO0mV7eA1oAbyjlrsBvKOeu0a8o57aZQ2RZZqtIIWJ_NqJBOGk1ozdnVGkpt4tkKujkDbERt5vE4mU4jYQJStuMr8ORH3a5wB23s84lnQ7r93BOGgC9cg_MOQdFdYZKEEWEg5569WNh3rgdwKc0bdwH5WBSd2rEtOGmV4DNQsv1YprXkiNjhZI4Ezm3Pu4M0AsctWuk3Wn8-d72YhKfQhv4K-V6lKCFFHPjwgFbJ8dPlYhmEsUCe8L-hHcbPR92p7UWEAdIWoBPFrk9NEVyV53WF8Tx47DsPONJNEHhRhiTYyyXxnQqNm5AQwc5SkwkyQSePX4SFHQHXzyzaRTibUm3-0qEy8ANgADdIhiL3NE0yxZ5kqbLak0XFNHuaaMhiTwUTV3po8D3N0lSppyiyKvZMy1R6qiiLYk-RNUXtSaYEIIqmynpPNXXJ7KmGZGg9VVdM6FUtVevpoqT1NEM2e4oqqT3dUOGTKEGjYik6EFINtaeqsFfvmYpm9CTNNKFPVYED2dBMqSebqgY4umUBoCVrOvInIfcmcGyqot6TdcnCv_jRFEW5J0v4WYVh1R46fQtwKHVDUa2epCiW0dMlVYJ2SdZhVpIlaj1JMmCygAVTEE0YTpJFA1gECfVk4NDEBpw9lRLwCIgQTIBF2QDRaJJugcRAdgoIxQSONFESgYpmmHLPQCnrICwQhyrC1DUQkwzy0VGSEnAJEtNAOpDdA4yigy5QGqLVg4AiA3mQl4wzMIAPEcjBhFHCiqEBfyB9aFFMhJSAAohWxHlIliUBYQU6VVOBSSqSrIA4JVSUoujAvaZIqC1wVkBFBF3KkqabMKoE3GiKJQIBjcrAEpEbU6WohowkNR3mI2qSiJ81GS0AVCmbmgF8GCAAUL5hIAcgLBgPtKLrYA0yiBrmIckwhi5LSMuygDFNt0DDAAgaBp5A_CqouKeD4wUkGYymp5m6BjZpSSh51QQxGSbIRDEtQ8b1jIVWO3zuV43fd2GtxbB-Vh5JFYsDV9JPh59GV_TDT_M4XkZvDw4eHx_3l3Y8D6bkCXZu--C2DpaABGvwTfTN9bw3SPWgD_-OZ2fHRHMGkvp0pZ69-fbknh4nI_OL_v72WD4Z_Or_Mr8wL5eAeS8NTpfzc8W8_dKXbi-8Jyl4tGbT-D5Snk-84Uy-eLhNrLvn-19m0XHwePu7_enk9PY375cPVwvJ_Xxhq_H7K-txIJ0-3Yw-G2-S-ZV-_XTliGPntzdvjq8c69GbkavkWO33pe_J9_jLV9O_l315cD24Vof2F6c_nGni081n-_q7ffWur0pX2vL3ZWQ9_vrhSnvz_lR1fdn-dDGWHy7G3t3H99ezh9GyP1GPw-cnMvtNe1I_Ts8Hl-pvbzT389nxk_Lxw8drafn06dY0Zsa9FU8-Xz_YrjqQ3zijc_H22y-3v93f2vL7i8j-8PX0-T4ajBX_-fSmf-u7x79_HZw7mjZKvsjyqf8usr8MQZ5UIQeZRg7Zw8GIqSf9Rj0a6g_dVVeAnGWB39K8ax2MWm8Bp3Hh0KUUcBIPjnqRAk7nwVE_U8CpPDi6JAu4tFIDUihP_hC3PqELrjwlArvi0L1LYpJ1QJx5-sh8PRDz4_Rz2S2x9cpWOVuHbN2zlZ26CeqeM5-MC5H5SOZbmEulK5uuaebo2DpmPjr1ndQnM__F_ChbvMx5ZrEI3Cas3jhMWWWBA10TczvU0TNfzvw383Us-lBHTf1bLq-KiEB8ECFpuMYQih8-BjHrw8bsy-EYF3QEaUAYX5BFdPwMKeA5JjQrSWEagxF6TGKWXpRxsmfaDpnaiYftvyQ2ZitpMpG1XrGH634QLvInDkAKUgKsOjCKN89LFEj_6ioN9umogltyW7SRPkLvF6yd2N4kosy5_sRLwML8dDObJxmefYcM4JkALJ475YfxJUr5QD8dAkc04QMOLn0ws9S1MvwLL7izPTmjQv1jmihWGSr1pI0j242IM_4GWVwM4L67xOfh6ekDXGPlEaRshAeWj-FaYai2l6HSIWhHslggA-XuiG0111mk3N1nypJBWzO2FAeA7EByeXAJazM6QFUfUAz4tDq0by_SBC3rEbKuFTlPgsSPaXmkItRUJlSyJQ45UmKayVNyOm-kchUE35KlMINtd0wclhiuiqMfwl4NMt1MICmtdWIDe7mi90yN-deDjJGDek5SC0LZ7WBMmSlstoT0QAUp6q1RupwqVkFbamAz07gvLdkmI8hX6nhix5CCw_KNKzZQbubon6v-gz9UUud0z8CKqlwRlYF2ls0Atj-u7d0Q2CWVhZO2C2nH6xLPOzKNuWLBzq3EUZIG4palwL6_rslfgpvwYPvOFUAGsLNNZATKkijaXpc0-o5DHCzVs8IiVygrcDvLBklc-tOEPb4q5IPtQtGxm5AOWeT6c6YOW6QEI3vm-jP2_DYq6arS_gMygTwRWBmwUBvrEPKebfVWzQJYCCdOebg_OlIQggdD2ZMCfqgoQ-1u-2UqFeNnHULW88qCKSzNIfFJHNL6Hl9IVbgXuYgSnTUvUel7XaK6JfYy8M88-jgue_jMFVgt9M5iG4buAvPehb2gpzgKqbEeoeh6ffY1YEXeRttKYV5kVymNNZvK23PRpNHgrxN5togv-ByC3NqeV1JE3rYm_5abyRLRkvCxUWCtr2wpA0_nYDh4RKJm6ZZ6dzfInHxJIHnba9xRncDfDfspBNlZIv1wYvtkbTPFml_nXurSjyBPaY6MJZjdNxUFjcq-otz8l82at_Rd-TPUqvvKml_iwQrSVSdWtL8u8xy5Mc4yit3JCT5o5troKuCuJYBVOpXdQtEnpJ2vS1qUKVZQ5AqqBLPzYn5H8FgZ5LHOmoyKrtcpokt_EhI7Ik4f_ruebhBWLfQLim0z3526Wc23Wm9Lu4Ss729nCJk_DFicNMmVU27e1RlWSZc2G9XTLa_LeI-9IHDOkQe8lMkz2grUC7I7Pw6mlFY1wfNjIZgKaccrixawAd0onjLQC6XDjsivC4e1v7JK6Z3XnOVlALtGzgy_kvnmba9LGIMgJKcJL-2t6d29rIHnWmBjQQ-ol9xMuflvV3_UvQjdxTmE2rIe8rYtTTJ18SWSheCxUUhbX1nyxg5Y8hM31r-zJab4ZWHkTS-2wPQjgNLjHOzABn6kSBTi0l8mMR38qItHKVjVvCvcBYFHbL98onIFGIl99ZPFHX2IT__Pn2tXIBduNPmKR1bx5QT02Ap9ncLZ-fnZyc3l57MUZUzoZRohSu4i9vGo-9klj5TrUxCi60UoBM-zl1GpmObS4wx0mh7maHxqFOqdm7-WoJ5WAcCndPZEwhhmcWuHk9AlXL7y_g1MsQHx7DAezeVRw7PsfELsmTNWStg5Yo6k6AF8PpUT9silHvkkf3RSi3u5WNoed-S0d4MkYjzAA8sA0u4JnpduVjke92FQDXKZTCBqTJ4b9J1eVeLToJcDeARYJx-ZHfHnYae9DVKltwu4UmW9fPRTMrG5c2edfOT8aHrg05d_1FPJoRoofQx8auSwaPquh08MuJo980gOwid4Hc9JmJ7f5lEagOfJQBoXDjsQyKVTgmiQFb3OwJEQ9vFR2fVlzhywr2HRpLd5eavdbV6y1QsPHH2UYfik2EUzrgzTW2sNakhvbnJUwHobZpLdXuVMIu1uWCjUB_cfAtdhFxc5S2YFrMlpBJNvLydDb2O-nMzq9cyXUzz37OgbV99pLx_9U0xrmzVUWLrTiggurJdRwPX1Mgp4R2-xM_ZoNRUpcEfNSUh-m7AWOettWvvpJcOdKWRHC3ZEpzc1d8amAeCUTHG31hgBcpiGxREnfra3fCEpyla9FylmtxUtFgtrZ7o1Rba603eXNDkABrKBEATzdw3pYjtK-Y3jd8T28EJk4L2M4No7Wl5CDK_0JUvbdzJy13VJeqGHltIL4gho0utwp3hz8KUy9MniuYYQn6_Dg2wPSC_K4UYrvd43jkMsPXwPgsUX2NDJoravaaJl6JaFtzKwPT2JL4np8XvIwE9drM5S88uGRchfj7qmsW_ImqhLhmXJ6WX1Q7oXTm8G4Of8YgCfXBIR9mIodsKFYjBBsR0nUCmf8h_RTfRbYdQfnXVg9uweoXDhuYsFCTuowjdXQRQLY3u5nLsh6VAKdGpvBVPsjGzHTaK3wnhhe14Hdi-eOwFjfyuIHUX8BxZv2EOI9NkAVhgpqDBkF56E9H6E6wuMVKe5W4C5BOz8ucB24ZHgwJIQpPJgTI9bkFLWsQV3KjwHiTC3AfcExkkW0GfDxxDMRgCTB3_jPXc-BjEWIFoNkxXnMyBK26qMnfpXWqMYBM7I9oGVEP8edcV9rZtqj1k5rZZUFSvXKPZiHiSeMIZg4fyZVCq_SKUZKSrjPTCPOBAQNz_0JbBkGwNQtKupLJgXFVj2L7D0vwMmEibLmDittNgAofD1rNTo-UOIngtXL5ZnOzwFV1QqVVRKX4aRybq6vrQabVTaJrQ-gGJ2_SkMEAvZBrVT0YVaRmL1GAHcvIBFGYFWXl4qNrmtYBsgVL7o1RrR4wm_GXEccJ5jD0worJe-bq5IvyJBfK9KJlqpYmeQQ5LvRKChMFl2pIq3Kyx6RXF_DXFrNeI-JnOyCOK5cJLE9ZI2jKqk5YrIxnPYdRbOdrOlbyvSm9CdzSA2OwLdUmakq0xgTzbA69aBXqOD4TwgvvskfIatMvE49q6vaKEqOvgfw0cRSOi5i6ijVIy_4lyFaRiAv71P3OUSF0YwSbb3LxX4qmVg9RbfXpVlAceBDwO8bu0YNdr5TACdOuQPPpgZRPU49mjqMSHLGNTEql5vwdzl6sLROunN0reCLHZo64jcQ4e8okujasxIrtP3PJfQyAm5UygM8Q13yAQ1f7UmzeJisLitGxhQsuo0hGN8oNDZU7GVsoZWg6GbqTSN3J09SUKISz-GubszJLiidLkujGOh5KW6VjdCaBshdL6uzbrEPbRnMPfjMHjsnD0tSRhjIAeJ3rh2aHcq6wcULoqrGUGucKuT3gqH9K8zSnwC_2PuCBkNQUnf2BPQQNkoKumE1PkPiBrygPi__wkB-797Bs27WFpR5FuoH6rYiuD3TKvchjWnjlLRE5s1MsK2RtMg8Z3OnrzJGhSNsYHxtcTFD8vTfuD6_qPsxuLbzS0uqdRuriGTAB9I0FWyZJbVlMEXKOaqJZkK15DAc2xrSdpOlmRUojWtJqeZaMcyq8EG50EjQTVb35OMGluUaRts88GPxnMAstYcyp7CeKLXGEos_bWMqQHC4JubJNbY27UfeXYym8eQM7heZnKwL13YPi732CO5uZmatGpusmW1s7fc4i5DMG_8uPad58HkVbtTxXUj6gnpg5I6a0oNh4XDPUnXaACjeJ09XSxbWhWzmvTwzVVVygMoZq1r25N12p6_RLHqffX6xfS_ZrkNEOZGCKvB-uvKaxdeAJnrOeiChFFm_MeBh1c3QOEDN4adcu5tjRXfKr_It-4WpY0a2wfjUfV1d2nIa6G7mh_yQrdZ60L3MO7XmPXfrhWLzfzSzw3BhyGd9KmhcEy8uEOfvAljL2C6r-T65fxeWwnAMmgf1EWfzQnZS_vwHXIenvW-9FElWADdkxRt3SAkzVy3iEqsZoQRuqAO-3HEVeuNQjY4vk75251xraWuUDiOAzSJGF9nlIdhAnssUMsVmeEjq5IrktXVSGyY___OSakYU_Yi3nSDX-e5alM_VV3fcogt_Jai8MOrDHrJ7BoyRcKKTAJIOX2X3N-G6dAXFDVliCf4fC4EW4K_Qn-ReCSuui6rZEKqWTUh8D6lHCm1TeGfVCfAK95WCaN_vRX29H9kCVvFe2nc4sAeM5iUsiz-iN1pmo394G3Eny7VqjWSuuIvOhXh7BmT-rtnYYS715UCVimo6ZzsPl-aRJD2TZOGOmofpWW6h_qtC0SSrteWpaT1AobapoAhiTWbS4vvYf6qhYsdPUlddfoUk-2L0F12hsQOvXUzMaWSmehq1YFUUtdS4bjvOJFA_YWksDzEYWVitAZaaob1bIlrVqC1sgIle0ZZHKUEO5D-9-xgRcv4akL-wYbqWwshzaXvuhzefRpd4RENdrweNl8PeCwof_1mLhMeBhtHKL0609iEwjLaEoa4CYMFthJb6iYMls0rW4zBMGq5oonapQPgq68zZajvySNErdIbTjPSrQQhb8FkKu0SitXEZfqS1DKXpfemtuQSd0cl0cuNYmFvb62IpXiha8sBM5MSxo_4KxOt9JG-5rU8cOnNry0HRudXlq2kNw3JXnxbHrF4FW5b0QbOs5CdVc5HbW0FXAE1za9k4ZLWblHILZWQvkO3LJLSa3VbyuQd8RbltW5uFmIQl11W5TQIu66E59JsBzwjnkm7pffXI3ZwjUYWeosp8KfuLD1Fxr6k58goft4ixG7sEbztQF8lW3WrQ8-ekDnEO0iOGHMED9OlP1SR3WsyxFyKHITKT7NkaJuQ8tCXXUnK71GJsrxpwLD4edMMTePj0HMBYxrH165r8ceAlh1YK17ptxUaTVoKDFPlwy_yn4HFH9HAKiOd2glekRsTb1oaV2sxx1W9aa0VN8QDphma0hZr6_Goda2KVBWtDWj5pYhcpk1CpSjV37jaWu3bzwxa2gpxPAnoAdXtjDj9tS7YddPMrLyoN2Bmbj4fSTYtscWyXJWd0oAUuTPXu57Ss_AwM3qgv-3M0pfatZLdyRyvSNaL7vAg95XsaDD99nPn8GDtl67_Dxe8Mdo=
```

### Screenshots

![Image](https://github.com/user-attachments/assets/02e6ef35-7bfa-46e1-b080-77f955a120ef)

![Image](https://github.com/user-attachments/assets/c3704482-1e43-46f0-971c-61a6cf37ff50)

Compare to build code provide, everything affected by one of the jewels is off: block chance, minion damage, energy shield, chaos resistance, etc.

**Comment by Peechey** [comment]
The math/scaling is fixed by #443 and will be in the next release.
The increased effect mod isn't supported in 0.2.0, as seen in your 2nd example, but it being blue in your first is obviously confusing and a separate, new issue.

**Comment by kenblair** [comment]
That makes sense, I didn't see that issue when I searched.  Thank you for working on this, looking forward to next release.

**Comment by kenblair** [comment]
@Peechey The calculations in 0.3.0 are still not correct. Would you like a new ticket with updated PoB screenshots or can this one be re-opened to address it?

**Comment by Peechey** [comment]
I'll reopen, is it a rounding issue or much more?

**Comment by kenblair** [comment]
It looks like a rounding issue.  PoE truncates in the UI but it holds the correct value, PoB seems to be rounding to nearest integer.

I will take some screenshots and provide the exact values but I have to go fetch dinner firest.

**Comment by kenblair** [comment]
Example:

![Image](https://github.com/user-attachments/assets/e6e958c0-9b43-45dc-aa31-9745d77ca00f)

5% increased block chance is calculating as 10% increased block chance, but should be 9% (5 * 1.8). (screenshot in ticket)

I think PoB is calculating it as 5 * 1.5 * 1.3 and then rounding 9.75 to 10.  If that's the case then there's two problems:

1. These values should be held to at least one decimal point, probably two.
2. The correct factor to use is 1.8 (1 + 0.5 + 0.3) while PoB is currently using 1.95 (1 * 1.3 * 1.8).

Also, it appears that at the very least shield block chance has the same issue:

PoB shows increased block as 81% and block chance as 77.83 which is 0.43 * 1.81.  The correct calculation is (0.25 * 1.75) * 1.81 where 0.25 is the block chance on the shield base and 1.75 is the 75% increased block chance on the shield.

I've tested the decimal places by checking in-game block chance while allocating/refunding increased block nodes and it is very consistent that the true 43.75% (or at least 43.7%) is being used even though the game truncates to 43%.  If PoB wants to display same as in-game it needs to truncate, but it should definitely hold the correct value behind the scenes.

**Comment by David-Yu-hk** [comment]
Allocated Titan's "Hulking Form".
Node "Arcane Surge on Critical Hit" is showing "0% chance to Gain Arcane Surge when you deal a Critical Hit".

**Comment by Hapseleg** [comment]
it seems theres a problem without "hulking form" as well

![Image](https://github.com/user-attachments/assets/c7cd1ea8-3dd4-4419-b7fc-28056bba04da)

![Image](https://github.com/user-attachments/assets/cabbdc5d-32fe-4cac-8458-75d6575eedba)

if I use a 29% jewel instead of a 30% jewel in POB its correct

`eNqtW91z4jgSfx7-ChdV93T5sPlOKtktkpBJrkiGhczM7b1sKbYAbYTF2XISZmv_9-uWbGMYZGRy-5Axdv9a_aFudbe9F7--L7jzSqOYifCy7p24dYeGvghYOLusf326Pe7Vf_2ldjEicv5lepUwjk8av9Q-XagfDqevlAOwVXd8TuL4kSzoZX1MwhmN6g6JfRoG1-sHjyKkdUeSaEblt2xV9w8P0HMSEV_SaIgc-4kUDyIAhIwSQCwICyfCf6HycySSJSxYd14ZfdM09w-jL-OnOkj16WLEyYpGE0mkE8Ofy3oftCMzekMW8BdQhCcAcU_cTq9-Wgq5SqJYVsFNlpQGOal30jARjiI6mE6pL9krvY6YvJ6T0C8sYsJVpX1IuGRLztAXKb1RprufWHtdE-2TkITfjCZFs_S8Tjm5kPuF_s7k_IqDFe2ZI-R-FjJJq2FGgsUirK7EBsJo_IRzCBQr2jGNafRKJNuSxshbLJ5ZWMVEDyQk1yK2sD9SjmgEUSsrASbUFxDoVdeoiByyKbWnrKRHCqgqzWF6DCa2dJUZHybQGFKcHeVEJNySUq6TTs-YdW7o-zrftE1U96G0yEo39FVgFO2XTcXy4G6UUzbd7kmz4XW9Xstze8ZAGs1XMfMJfyDvbJEsIGU-kRe6XrB51jXvltlchpATTNhGr2XC3rKIHgC7Fjw4BDYnIj5Awwc4o-9IGPR9P4GjfLX2mNcqiyEb3nCy-udIfB_6611VxvVrGKm8WjiQS70zpWMIGDz4nzm1hawXSeNurbPrlq81o2G64Mou1Qwp9eefwcZjIqldll1L03BLLYvERcuWct1h2RL-m4gKZkLgbjO1TnploIqGmiwZVEo2EmnKXerbYyoYYBDSaLaazBnlgUXqL1BnFrsmSxv9YQMU0VYbYXO5Spu5CK3oKzynqq72SuLimdA5KzeEJrcLBgqVKgACaluTjyLxJ1b9vBqsHy1EElm6UhNbKZAdZ7rHGdMg8e3Oz7x5ueLQlNmqkaNATs4rQftSEv_lRgQza6OpRSohNuWbJMslRC3uBlsGeE5DNc8K5dFxy4L6C2xlq1jFE91-gTW19QJ5lWK_yhbEXhcsM7aWsSG2XiB35wOkigUkXdWeP4hC3ja6Bto3q15MEVr2hCPxBpLPcfYRV6OGYmxdkRhFiWj4Y2XNf4PcaoFBGEBdB4FgvcY2YtcyV8l0Gjs-9LREDsG9l_W68wz3smuoJWOa_tCIJ7aAxBvHN0QSJ0hr_m8kYiSUDTUZiimJ_DmCbgnnz5A5kNP6Lv7aAnrZbrg4VYMtvLpfLEUkHfqO_4xIJFeX9SnhMdWE6g7wiSULVfcOaYrzujOZi7d-8Ip6PwnB4wzkkOWShsEGj6eIUodkScdHIZSO-MNZkFjCGaf3cYxCF-Zp9wEa3gkFCACnWtNrNo7abqt9dtQ4a3Xhb6vXaB-1mt1W56jZ81rNI6_TddtHzZbX7By1u24DbrQ67lG702l7R57XcVtwDRwA2ml1j5petwMMGk1g5gEKaLpur4d2xMaSRKv-pjQhA-UlKLQ12FtLi6p9uvg6HqqLT3Mpl_H56enb29vJksi5mNJ3OBpPYDOcLgEERjmOXxjnx8j1tA__Xc36_cGU-P4qmB2D5_jo7Oq337_9fvvyn_7Tozccfnsi3e9Xd9Or75z9GP_5W4yoy0u18Gm28oUeJcZajPSXMiXKqWxZd5ikC_yZblSAF1EXmIYiBsZPmcAJFbHnRNLsAeyM90ftHWAWyvw6llF6XTSx9pryi3ad9oh2oPaUdp32ReqjgmO177SPMok3hAQFYFepLY7bDi8ehdTP8Gb242KCNo-dGHb9Z7qIr1aQ3m6xWtuaPaX7FqknVOrIK2Ky4W1ApyTheP-3hHCGYeQW7w71DDkU0SJvrYEVhBGewZrj02qJFusPh2mApKs6LFhHrhYcL68J97XS9-EyAd-q6fOCxf4fmFxwbKwcocbcg9vbwfXT_bdBmmCKELX__giTxTPOUPW_64NjQlXB5MTJc6wvL-vfGH1TgtxQSRiHNOkLzskypnnoK6FTDTjgSrgpKujCszH0bl5rAjOnwTuNIFPNvkMWjBg1ypU_3yOUXhCrcEzIJm449TUz0mXdNeQ5Xf8bLKXG6mYuOOk2qoMPS7CQ4wk3rpw-3WMJiXsTQotNmY-nX7nLcSdrqhK75CMUo7_TmtTMQ43RTQz0QzNYD8dN6PRpiVXVPN5oVf3UDL-hPjHqrh-awXlLKcI77Ot3c8mpSjg9ilBtcgiaPuNYQRo9O-A0JzEz_CLnNEqPcxOnB8hRGUlp4OjTxsinQFFiKzV-M1gIn5mher5k0AGflQRNOnExRTsrD9nNuYjBH0UaMyvdURhtmHYnJW5IG3ODC_TTEk2y2YRBifRxSaCoHNx_FSzQHaohZLbIypIG1DgfZ6Pa7o-z2e7DP87xForRF6O_06dm-FfJsH7ZwUVXOlZMMLA-xgHj62McsCFbHIweb5cia-y4vAjJW8ed4OxpWeynHeXBHHTfezBcteUHo9UBcEOnFDQoPQFympLgkEl4A8aQJYFhyUqJtTuLrLWrxEufhTs1rcxRR3f6GqosAWiSPYzgML8rKRftOOWjpTtKOH5KIPjHGP70uu0jzHA4nixJGGTsvuwq0td-sLSekDHwVNORG5zBf9SGIV2sdjAyy3VxmrV1am6CjVY61JnICDvrH0Isfr-sN9xu7wQa56bbPmt4bX0_bTLxp-osoQK_YeDGSG2_bFmk_Pdl_bjRbHdOuq2u22z3ul39-vLiXkJnm3a9eJ03vWZ-SUz1e_jvlCxFqBA4J9F9JvBQijb0ZGRMoPBZnTvj_nhQewTlkKCGjjseilg6gwWNCA9q1xGZShqcO7hGbRTRKXs_d_6K8KOrc_ek_fe_6BvlYxKwJB5iSpqwH2s6_ASrNoEmeAN01jgrwibQiXOcUuidntMrsDLlmP733HFrmvzcUYAa9Euc-RBe-OjrchaRgMaOpnGkcJQ0tcbZPxwW-hEl4HBHr-CIqebhjPTkx0mnECxM8WqiAY27-rbMUXLjdy_temEEUEaRfYJwilbdtH9zh_2v6JwuhJw7E1AplDQqOGKcPK9qCq1Mce701obQKhYM4dX-gi0B3Zr8-5-ei1a4B3acsxnuFLOVmu5BVip_7ECUCgdWDKXTLPL3VTuppFPdWe1RSHwTXp3TA0EGSUBRWNVnQsp1ViIBmikYRdauRRQlS9jB_yeXllA091K0dm4LnCyZYjcVLp0kciHVqHD0_HU8xCSk50afuXjFgy-bIrqZICaAXsTxKkBUnVYJ0V8knMoKAFUnOs3KiOpqNKrbqgrkinJ5gDecyRu-arLGjXGvV5JLBCsnayMrG8AonppU3wcA2h5rawYq1TuFSXe2gI1-XuXtUMUidxRqR1nJhEL-HGk6oCFoVeGgjm41GBbhlM3SQ1z_SI9xBcrvbAT5iBOfzgUPaJSuSbF4ST_3zYbCXTcX1QDYeOWZwfaB8ver2Qg4H0K7jca-BQvfC2ew9h5M8SV2jtmrGdw5QD5c6wCYOnXXiOxTtl30i_wLaPzmF6qzYKJGziIJ5YTyaWHdtoWOlQ2Te2-EVX0Ga9qiqjsCt9i2SVvu2R5YPonKbVpm1Mkc8ouyY_zTO5HSvYgfm0DueglpHG_jG_tU2_xapVocwB1bB0x8oTqKatqln9BAG6PKjGJW2IPMkn--UqN3VoKJ2YzxL1M1hwAh1TCligu2rdd0LWLU1nbXc3yntdt00L1lyVX3curXL7WL05_-55L_AYJgS4A=`

**Comment by LocalIdentity** [comment]
Appears to be fixed at some point. The 30% jewel now correctly shows 19% for the crit node

![Image](https://github.com/user-attachments/assets/9c6aff67-1dbf-4262-95ea-54c95f204340)
